.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ALTTAB" "1" "November 2017" "" ""
.
.SH "NAME"
\fBalttab\fR \- the task switcher
.
.SH "SYNOPSIS"
\fBalttab\fR [\fB\-w\fR \fIN\fR] [\fB\-mm\fR \fIN\fR] [\fB\-bm\fR \fIN\fR] [\fB\-mk\fR \fIN\fR] [\fB\-kk\fR \fIN\fR] [\fB\-t\fR \fINxM\fR] [\fB\-i\fR \fINxM\fR] [\fB\-s\fR \fIN\fR] [\fB\-theme\fR \fIname\fR] [\fB\-bg\fR \fIcolor\fR] [\fB\-fg\fR \fIcolor\fR] [\fB\-frame\fR \fIcolor\fR] [\fB\-font\fR \fIname\fR] [\fB\-v\fR|\fB\-vv\fR]
.
.SH "DESCRIPTION"
The task switcher designed for minimalistic window managers or standalone X11 session\.
.
.P
Unlike task switchers integrated in most simple WMs, \fBalttab\fR features visual interface and convenient tactile behaviour, switching windows on releasing Alt key\.
.
.P
Being lightweight and depending only on core X11 libs, it still features customizable look and behaviour\.
.
.SH "OPTIONS"
Most command line options have corresponding X resource\.
.
.TP
\fB\-w\fR \fINUMBER\fR
resource: alttab\.windowmanager
.
.br
default: autodetect
.
.IP
Control how to obtain window list and set focus\. \fINUMBER\fR may be 0, 1 or 2:
.
.IP
\fI0\fR: No WM, raw X\.
.
.IP
Only "leader" windows are listed, since Xlib has no other means to recognize main application window\. List order is random\. Running \fB\-w 0\fR under WM is discouraged: hidden windows or windows on another desktops will not be listed; instead, some strange windows may be included\. Nevertheless, this mode is suitable for dwm(1) and other managers which don\'t expose window list via EWMH\.
.
.IP
\fI1\fR: EWMH compatible\.
.
.IP
Compatible WM list is in [SEE ALSO] below\. Tested in xmonad(1) (EWMH must be allowed, details in doc/xmonad\.md), i3(1), evilwm(1), xfwm4(1), metacity(1)\.
.
.IP
\fI2\fR: Ratpoison\.
.
.IP
Alttab uses ratpoison(1) own perfect remote control capability\. Additionally, alttab registers itself in its "unmanaged list" automatically\.
.
.TP
\fB\-mm\fR \fINUM\fR
resource: alttab\.modifier\.mask
.
.br
default: \fI8\fR (Mod1Mask aka left Alt)
.
.IP
Main modifier mask\. See /usr/include/X11/X\.h\.
.
.TP
\fB\-bm\fR \fINUM\fR
resource: alttab\.backscroll\.mask
.
.br
default: \fI1\fR (ShiftMask)
.
.IP
Backward scroll modifier mask\.
.
.TP
\fB\-mk\fR \fINUM\fR
resource: alttab\.modifier\.keysym
.
.br
default: \fI0xffe9\fR (XK_Alt_L aka left Alt)
.
.IP
Keysym of main modifier alone\. See /usr/include/X11/keysymdef\.h\. Keep in sync with \fB\-mm\fR\.
.
.TP
\fB\-kk\fR \fINUM\fR
resource: alttab\.key\.keysym
.
.br
default: \fI0xff09\fR (XK_Tab)
.
.IP
Keysym of main key\.
.
.TP
\fB\-t\fR \fINNxMM\fR
resource: alttab\.tile\.geometry
.
.br
default: \fI112x128\fR
.
.IP
Size of a single tile (mini\-window)\. If switcher doesn\'t fit the screen, tile may be thinner\.
.
.TP
\fB\-i\fR \fINNxMM\fR
resource: alttab\.icon\.geometry
.
.br
default: \fI32x32\fR
.
.IP
Size of icons\.
.
.TP
\fB\-s\fR \fINUMBER\fR
resource: alttab\.icon\.source
.
.br
default: 2
.
.IP
Source of icons\. \fINUMBER\fR must be between 0 and 3:
.
.IP
\fI0\fR: Use icons from X11 window attributes only\.
.
.IP
\fI1\fR: Load icon from file if not found in window attributes\.
.
.IP
Alttab searches for PNG icons under:
.
.IP
/usr/share/icons
.
.br
/usr/local/share/icons
.
.br
~/\.icons
.
.br
~/\.local/share/icons
.
.IP
Directory structure should obey freedesktop standard, but desktop files are ignored, instead file name is expected to be equal to application class\.
.
.IP
\fI2\fR: Prefer icon from file when it matches requested size better (see \fB\-i\fR option)\.
.
.IP
\fI3\fR: Use icons from files only\.
.
.TP
\fB\-theme\fR \fIname\fR
resource: alttab\.theme
.
.br
default: \fIhicolor\fR
.
.IP
Desktop theme for application icons\. Used when \fB\-s\fR is 1, 2 or 3\.
.
.P
The following three options accept color names or \fI#rrggbb\fR\. Special value \fI_rnd_low\fR or \fI_rnd_high\fR produce random color from lower or upper RGB space respectively\.
.
.TP
\fB\-bg\fR \fIcolor\fR
resource: alttab\.background
.
.br
default: \fIblack\fR
.
.IP
Tile background color\.
.
.TP
\fB\-fg\fR \fIcolor\fR
resource: alttab\.foreground
.
.br
default: \fIgrey\fR
.
.IP
Foreground color\.
.
.TP
\fB\-frame\fR \fIcolor\fR
resource: alttab\.framecolor
.
.br
default: \fI#a0abab\fR
.
.IP
Color of frame around selected tile\.
.
.TP
\fB\-font\fR \fIname\fR
resource: alttab\.font
.
.br
default: \fIxft:sans\-10\fR
.
.IP
Label font name in format: \fBxft:fontconfig_pattern\fR, like in emacs(1) and rxvt(1)\. See [SEE ALSO] for fontconfig pattern\. It\'s neither GTK font pattern nor legacy XLFD\.
.
.P
Your Xresources database probably already has *background, *foreground or *font wildcard definitions, which alttab will obey\. Precedence order (preferred first):
.
.P
alttab\.font resource,
.
.br
\fB\-font\fR option,
.
.br
wildcard resource like *font in xfd: format\.
.
.TP
\fB\-v\fR, \fB\-vv\fR
resource: no
.
.br
default: silent
.
.IP
Verbosity\.
.
.TP
\fB\-h\fR
short help
.
.SH "CAVEATS"
Run alttab after WM, or it will fail to detect it\.
.
.SH "AUTHOR"
Copyright 2017 Alexander Kulak \fB<sa\-dev AT rainbow POINT by>\fR\.
.
.SH "REPORTING BUGS"
Please report issues on github \fIhttps://github\.com/sagb/alttab/issues\fR\.
.
.SH "SEE ALSO"
skippy\-xd(1)
.
.P
EWMH compatible WM list \fIhttps://en\.wikipedia\.org/wiki/Extended_Window_Manager_Hints#List_of_window_managers_that_support_Extended_Window_Manager_Hints\fR\.
.
.P
Description of fontconfig pattern \fIhttps://www\.freedesktop\.org/software/fontconfig/fontconfig\-user\.html\fR\.
