name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build

    steps:
    - uses: actions/checkout@v2

    - name: install build dependencies
      run: sudo apt-get -y install libx11-dev libxmu-dev libxft-dev libxrender-dev libxrandr-dev libpng-dev libxpm-dev uthash-dev autoconf automake

    - name: create build directory
      run: mkdir -p ${{ github.workspace }}/build

    - name: configure
      run: cmake ..

    - name: make
      run: cmake --build .

    - name: check
      run: ctest
